### ISSUE TITLE
6.9-rc4 + sched_ext compile fails, related to "scx_tick"

### ISSUE THREAD

**Issue by MichaelDeets** [sched-ext/sched_ext#183]
While trying to compile 6.9-rc4 with sched_ext applied, the build fails due to `scx_tick` being called within `kernel/sched/core.c`. 

Specifically, it calls `scx_tick(rq)`, while the definition within `kernel/sched/ext.h` uses just `void`. Changing the definition from void (within `kernel/sched/ext.h`) to `struct rq *rq` results in the kernel compiling without errors. Given I have not tested this kernel yet, I do not want to submit a PR; I could submit one after testing, but I would rather refer this issue to someone who knows what they are doing.

I'm currently using 6.8.7, and currently have a working configuration (can use scx_lavd for example). I'm extremely novice, so I'm hesitant to say anything; I would hate to waste people's time. 

EDIT: Thanks I'm just going to test out and will report back if anything interesting pops up

**Comment by ptr1337** [comment]
Weve succesfully compiled 6.9rc4 with following patchset:
https://github.com/CachyOS/kernel-patches/blob/master/6.9/sched/0001-sched-ext.patch

Please give it a try.

**Comment by htejun** [comment]
https://github.com/sched-ext/sched_ext/pull/184 should fix it. Thanks.

**Comment by MichaelDeets** [comment]
@ptr1337 @htejun Thanks! I'll test it out and come back

**Comment by MichaelDeets** [comment]
Compiled fine, though I had to adjust the [patch provided by CachyOS](https://github.com/CachyOS/kernel-patches/blob/master/6.9/sched/0001-sched-ext.patch) as some of the changes had already been applied. Was able to run scx_lavd just fine and everything seems to work well.
