### ISSUE TITLE
How to efficiently develop the kernel under the sched-ext framework?

### ISSUE THREAD

**Issue by violence-max** [sched-ext/sched_ext#19]
We want to modify the kernel based on the sched-ext framework to implement certain features. However, kernel development is not only challenging from a technical perspective but also time-consuming when it comes to compiling the entire kernel. Moreover, this time consumption can reach a staggering 70 minutes without any kernel module trimming. I would like to inquire if there are existing proven methods to quickly make kernel changes and reduce the compilation time.

**Comment by ByteLab-David** [comment]
Hi, 70 minutes is a long time. `make localmodconfig` will automatically detect what devices you have on your host and will compile the minimum modules required to build a kernel you can run. In general, I recommend building either a smaller .config, or buying a host with more cores / RAM.
