### ISSUE TITLE
"rusty" scheduler causing stalls and systemd failures

### ISSUE THREAD

**Issue by SQalliT** [sched-ext/sched_ext#202]
I'm encountering recurring errors with the "rusty" BPF scheduler that are resulting in systemd service failures and Blackscreen on login for a number of minutes. Here's a breakdown of the issues:

-     Kernel Errors: The sched_ext BPF scheduler named "rusty" is consistently erroring out and being disabled by the kernel.
-     Runnable Task Stalls: Tasks (kworker, Xwayland) are experiencing significant stalls (30+ seconds) that seem related to the scx_watchdog_workfn function of the scheduler.
-     Systemd Impacts: The scheduler failure is causing scx.service to fail repeatedly. This triggers attempted restarts and impacts other dependent services (e.g., KDE components).

This issue doesnt seem to be present when using "scx_simple".

CachyOS Linux x86_64
Kernel: 6.8.9-5-cachyos (issue persists on 6.9.rc7-3 too)
DE: KDE Plasma 6.0.4
CPU: AMD Ryzen 9 5950X

This is my first time submitting a Github issue, so please let me know if I should include any additional information or if I've done something incorrectly.

`May 09 13:14:15 ra kernel: sched_ext: BPF scheduler "rusty" errored, disabling 
May 09 13:14:15 ra kernel: sched_ext: runnable task stall (kworker/31:1[311] failed to run for 39.079s) 
May 09 13:14:15 ra kernel:    scx_watchdog_workfn+0x154/0x1e0 
May 09 13:14:15 ra kernel:    process_one_work+0x193/0x3c0 
May 09 13:14:15 ra kernel:    worker_thread+0x393/0x540 
May 09 13:14:15 ra kernel:    kthread+0xd2/0x100 
May 09 13:14:15 ra kernel:    ret_from_fork+0x34/0x50 
May 09 13:14:15 ra kernel:    ret_from_fork_asm+0x1a/0x30 
May 09 13:14:15 ra systemd[1]: scx.service: Main process exited, code=exited, status=1/FAILURE 
May 09 13:14:15 ra systemd[1]: scx.service: Failed with result 'exit-code'. 
May 09 13:14:16 ra systemd[1]: scx.service: Scheduled restart job, restart counter is at 1. 
May 09 13:14:16 ra systemd[1]: Started Start scx_scheduler. 
May 09 13:14:16 ra systemd[1246]: plasma-ksplash.service: start operation timed out. Terminating. 
May 09 13:14:26 ra kernel: rcu_tasks_wait_gp: rcu_tasks grace period number 41 (since boot) is 10096 jiffies old. 
May 09 13:14:26 ra xdg-desktop-por[1297]: Failed to create file chooser proxy: Error calling StartServiceByName for org.freedesktop.impl.portal.desktop.kde: Timeout was reached 
May 09 13:14:26 ra xdg-desktop-por[1297]: No skeleton to export 
May 09 13:14:36 ra plasma_waitforname[1284]: org.kde.knotifications: WaitForName: Service was not registered within timeout 
May 09 13:14:36 ra systemd[1246]: dbus-:1.2-org.kde.KSplash@0.service: Main process exited, code=exited, status=1/FAILURE 
May 09 13:14:36 ra systemd[1246]: dbus-:1.2-org.kde.KSplash@0.service: Failed with result 'exit-code'. 
May 09 13:14:47 ra kernel: sched_ext: BPF scheduler "rusty" errored, disabling 
May 09 13:14:47 ra kernel: sched_ext: runnable task stall (kworker/31:1H[426] failed to run for 30.658s) 
May 09 13:14:47 ra kernel:    scx_watchdog_workfn+0x154/0x1e0 
May 09 13:14:47 ra kernel:    process_one_work+0x193/0x3c0 
May 09 13:14:47 ra kernel:    worker_thread+0x393/0x540 
May 09 13:14:47 ra kernel:    kthread+0xd2/0x100 
May 09 13:14:47 ra kernel:    ret_from_fork+0x34/0x50 
May 09 13:14:47 ra kernel:    ret_from_fork_asm+0x1a/0x30 
May 09 13:14:47 ra systemd[1]: scx.service: Main process exited, code=exited, status=1/FAILURE 
May 09 13:14:47 ra systemd[1]: scx.service: Failed with result 'exit-code'. 
May 09 13:14:47 ra systemd[1]: scx.service: Scheduled restart job, restart counter is at 2. 
May 09 13:14:47 ra systemd[1]: Started Start scx_scheduler. 
May 09 13:14:51 ra xdg-desktop-por[1297]: Failed to create app chooser proxy: Error calling StartServiceByName for org.freedesktop.impl.portal.desktop.kde: Timeout was reached 
May 09 13:14:51 ra xdg-desktop-por[1297]: No skeleton to export 
May 09 13:14:56 ra kernel: rcu_tasks_wait_gp: rcu_tasks grace period number 41 (since boot) is 40208 jiffies old. 
May 09 13:14:56 ra systemd[1246]: plasma-ksplash.service: State 'stop-sigterm' timed out. Killing. 
May 09 13:14:56 ra systemd[1246]: plasma-ksplash.service: Killing process 1293 (ksplashqml) with signal SIGKILL. 
May 09 13:15:06 ra systemd[1246]: plasma-kcminit.service: start operation timed out. Terminating. 
May 09 13:15:06 ra systemd[1246]: xdg-desktop-portal.service: start operation timed out. Terminating. 
May 09 13:15:06 ra systemd[1246]: xdg-desktop-portal.service: Failed with result 'timeout'. 
May 09 13:15:06 ra systemd[1246]: Failed to start Portal service. 
May 09 13:15:17 ra systemd[1246]: Started Konsole - Terminal. 
May 09 13:15:17 ra systemd[1246]: Starting Portal service... 
May 09 13:15:18 ra systemd[1246]: plasma-ksplash.service: Main process exited, code=killed, status=15/TERM 
May 09 13:15:18 ra systemd[1246]: plasma-ksplash.service: Failed with result 'timeout'. 
May 09 13:15:18 ra systemd[1246]: Failed to start Splash screen shown during boot. 
May 09 13:15:18 ra systemd[1246]: plasma-kcminit.service: Failed with result 'timeout'. 
May 09 13:15:18 ra systemd[1246]: Failed to start KDE Config Module Initialization. 
May 09 13:15:18 ra systemd[1246]: Dependency failed for KDE Configuration Module Initialization (Phase 1). 
May 09 13:15:18 ra systemd[1246]: plasma-kcminit-phase1.service: Job plasma-kcminit-phase1.service/start failed with result 'dependency'. 
May 09 13:15:18 ra kernel: sched_ext: BPF scheduler "rusty" errored, disabling 
May 09 13:15:18 ra kernel: sched_ext: runnable task stall (Xwayland[1374] failed to run for 30.634s) 
May 09 13:15:18 ra kernel:    scx_watchdog_workfn+0x154/0x1e0 
May 09 13:15:18 ra kernel:    process_one_work+0x193/0x3c0 
May 09 13:15:18 ra kernel:    worker_thread+0x393/0x540 
May 09 13:15:18 ra kernel:    kthread+0xd2/0x100 
May 09 13:15:18 ra kernel:    ret_from_fork+0x34/0x50
 May 09 13:15:18 ra kernel:    ret_from_fork_asm+0x1a/0x30 
May 09 13:15:18 ra systemd[1]: scx.service: Main process exited, code=exited, status=1/FAILURE 
May 09 13:15:18 ra systemd[1]: scx.service: Failed with result 'exit-code'. 
May 09 13:15:18 ra kwin_wayland[1290]: kf.windowsystem: static bool KX11Extras::mapViewport() may only be used on X11 
May 09 13:15:18 ra systemd[1246]: Starting KDE Session Management Server... 
May 09 13:15:18 ra kwin_wayland_wrapper[1484]: The XKEYBOARD keymap compiler (xkbcomp) reports: 
May 09 13:15:18 ra kwin_wayland_wrapper[1484]: > Warning:         Unsupported maximum keycode 708, clipping. 
May 09 13:15:18 ra kwin_wayland_wrapper[1484]: >                  X11 cannot support keycodes above 255. 
May 09 13:15:18 ra systemd[1246]: Started Unlock kwallet from pam credentials. 
May 09 13:15:18 ra kwin_wayland_wrapper[1484]: > Warning:         Could not resolve keysym XF86KbdInputAssistPrevgrou 
May 09 13:15:18 ra kwin_wayland_wrapper[1484]: > Warning:         Could not resolve keysym XF86KbdInputAssistNextgrou 
May 09 13:15:18 ra kwin_wayland_wrapper[1484]: Errors from xkbcomp are not fatal to the X server 
May 09 13:15:18 ra systemd[1246]: Starting KDE Daemon 6... 
May 09 13:15:18 ra pam_kwallet_init[1490]: 2024/05/09 13:15:18 socat[1490] W address is opened in read-write mode but only supports read-only 
May 09 13:15:18 ra kcminit[1486]: Initializing "/usr/lib/qt6/plugins/plasma/kcms/systemsettings/kcm_fonts.so" 
May 09 13:15:18 ra kcminit[1486]: Initializing "/usr/lib/qt6/plugins/plasma/kcms/systemsettings/kcm_style.so" 
May 09 13:15:18 ra systemd[1246]: Started KDE Daemon 6. 
May 09 13:15:18 ra kded6[1487]: org.kde.libkbolt: Failed to connect to Bolt manager DBus interface: 
May 09 13:15:18 ra kded6[1487]: org.kde.bolt.kded: Couldn't connect to Bolt DBus daemon 
May 09 13:15:18 ra NetworkManager[1054]: <info> [1715256918.4972] agent-manager: agent[c3df4899cf53b27f,:1.38/org.kde.plasma.networkmanagement/1000]: agent registered 
May 09 13:15:18 ra NetworkManager[1054]: <info> [1715256918.4973] policy: auto-activating connection 'VM9490937' (9401069b-a2e6-45e4-852a-c1f48f44da58) 
May 09 13:15:18 ra NetworkManager[1054]: <info> [1715256918.4975] device (wlan0): Activation: starting connection 'VM9490937' (9401069b-a2e6-45e4-852a-c1f48f44da58) 
May 09 13:15:18 ra NetworkManager[1054]: <info> [1715256918.4975] device (wlan0): state change: disconnected -> prepare (reason 'none', sys-iface-state: 'managed') 
May 09 13:15:18 ra NetworkManager[1054]: <info> [1715256918.4977] manager: NetworkManager state is now CONNECTING 
May 09 13:15:18 ra kded6[1487]: QDBusObjectPath: invalid path "/modules/plasma-session-shortcuts" 
May 09 13:15:18 ra kded6[1487]: kf.dbusaddons: The kded module name "plasma-session-shortcuts" is invalid! 
May 09 13:15:18 ra systemd[1]: scx.service: Scheduled restart job, restart counter is at 3. 
May 09 13:15:18 ra NetworkManager[1054]: <info> [1715256918.5076] device (wlan0): set-hw-addr: reset MAC address to 7C:50:79:07:6F:DE (preserve) 
May 09 13:15:18 ra NetworkManager[1054]: <info> [1715256918.5086] device (wlan0): state change: prepare -> config (reason 'none', sys-iface-state: 'managed') 
May 09 13:15:18 ra NetworkManager[1054]: <info> [1715256918.5087] device (wlan0): Activation: (wifi) access point 'VM9490937' has security, but secrets are required. 
May 09 13:15:18 ra NetworkManager[1054]: <info> [1715256918.5087] device (wlan0): state change: config -> need-auth (reason 'none', sys-iface-state: 'managed') 
May 09 13:15:18 ra NetworkManager[1054]: <info> [1715256918.5088] sup-iface[36a9694bd6cd1c04,0,wlan0]: wps: type pbc start... 
May 09 13:15:18 ra NetworkManager[1054]: <info> [1715256918.5090] device (wlan0): supplicant interface state: disconnected -> inactive 
May 09 13:15:18 ra NetworkManager[1054]: <info> [1715256918.5090] device (p2p-dev-wlan0): supplicant management interface state: disconnected -> inactive 
May 09 13:15:18 ra wpa_supplicant[1111]: wlan0: WPS-PBC-ACTIVE 
May 09 13:15:18 ra systemd[1246]: Started dbus-:1.2-org.kde.KSplash@1.service. 
May 09 13:15:18 ra systemd[1246]: Started KDE Session Management Server. 
May 09 13:15:18 ra systemd[1]: Started Start scx_scheduler. 
May 09 13:15:18 ra systemd[1246]: Starting KDE Plasma Workspace...`

**Comment by sozforex** [comment]
The https://github.com/sched-ext/scx repo likely is a better place for issues with specific schedulers.
It is possible that you have not received a reply because no one wants to try to read the log with the the way it is formatted right now.
If you use triple backquotes before and after the pasted text, it should become much more readable.

**Comment by ByteLab-David** [comment]
Hi @SQalliT, could you please reopen this issue in the scx repo as @sozforex suggested? And yes, it'd be great if you could please post logs that are formatted so they're a bit easier to read. I haven't been able to reproduce the login issue myself but it's possible that https://github.com/sched-ext/scx/pull/332 may help

**Comment by SQalliT** [comment]
I had stopped using my scx service for a while, and since updating between my initial post and now the issue has seemingly been resolved.

**Comment by SQalliT** [comment]
It was not solved. https://github.com/sched-ext/scx/issues/354 added the issue to the recommended repo
