### ISSUE TITLE
scx_pair example require at least 1 cpu?

### ISSUE THREAD

**Issue by inwardvessel** [sched-ext/sched_ext#28]
some of the code in the userspace program does something like `nr_cpus / 2`, so maybe it would be good to have a requirement that cpu count has to be at least 2. if all in agreement, I can help make this small change.

**Comment by htejun** [comment]
Oh yeah, scx_pair  doesn't make nleees there are more than one CPUs.

**Comment by inwardvessel** [comment]
tested your update and can confirm it errors out early if `nr_cpu_ids == 1`
