### ISSUE TITLE
scx_pair example constraint needed on stride input?

### ISSUE THREAD

**Issue by inwardvessel** [sched-ext/sched_ext#29]
the pair example program makes use of a stride value. the default is the cpu count divided by 2. optionally, a command line option `-S` is available to override the stride. it seems though that certain inputs will result in the storage of cpu id's that are greater than what is available on a given system while excluding cpu id's that should be available. for example logging the `pair_cpu` array on a 12 cpu system:

```
root@(none):/mnt# ./scx_pair     
6 7 8 9 10 11 0 1 2 3 4 5 
root@(none):/mnt# ./scx_pair -S 6
6 7 8 9 10 11 0 1 2 3 4 5 
root@(none):/mnt# ./scx_pair -S 5
5 6 7 8 9 0 1 2 3 4 15 16
root@(none):/mnt# ./scx_pair -S 4
4 5 6 7 0 1 2 3 12 13 14 15
```

some cpu id's are present that are greater than 11. it causes a bpf error in these cases due to an expected cpu not being found. I might be missing something, but the default stride of `nr_cpus/2` makes sense to me but it's not clear what a stride of a different value would imply.

**Comment by htejun** [comment]
Probably the only other value which may make sense is 1 where the neighboring CPUs are paired. I've never seen SMT CPU numbers laid out that way but also can't think of a reason why that wouldn't be possible. Anyways, added error handling so that incorrect stride values fail with a clear error message. Thanks.

**Comment by inwardvessel** [comment]
tested your update and can confirm the array in question contains valid cpu's and errors out when needed. it's nice to see the pairs being logged out too.
