### ISSUE TITLE
Error while running ./scx_simple: BPF program load failed

### ISSUE THREAD

**Issue by isomorphik7** [sched-ext/sched_ext#45]
#### Environment:
- Kernel Version: 6.4.0+

#### Steps to Reproduce:
```
# cp /boot/config-6.5.0-0.rc7.20230822gitf7757129e3de.51.fc40.ppc64le .config
# make localmodconfig
# make menuconfig
# grep -i class_ext .config
CONFIG_SCHED_CLASS_EXT=y
#
# make -j8 vmlinux modules
# #Building inird.img...
# kexec vmlinux --initrd=initrd.img --command-line="$(cat /proc/cmdline)"
# cd linux/tools/sched_ext/
# make CC=clang LLVM=1 -j8
# ./scx_simple
libbpf: prog 'simple_enqueue': BPF program load failed: ERROR: strerror_r(524)=22
libbpf: prog 'simple_enqueue': -- BEGIN PROG LOAD LOG --
JIT does not support calling kernel function
processed 0 insns (limit 1000000) max_states_per_insn 0 total_states 0 peak_states 0 mark_read 0
-- END PROG LOAD LOG --
libbpf: prog 'simple_enqueue': failed to load: -524
libbpf: failed to load object 'scx_simple'
libbpf: failed to load BPF skeleton 'scx_simple': -524
scx_simple: scx_simple.c:83: int main(int, char **): Assertion `!scx_simple__load(skel)' failed.
Aborted (core dumped)
#
# clang -v
clang version 18.0.0 (https://github.com/llvm/llvm-project.git b90d6b237ff67498213059d0d3639ac965d4e5bf)
Target: powerpc64le-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/bin
Found candidate GCC installation: /usr/lib/gcc/ppc64le-redhat-linux/13
Selected GCC installation: /usr/lib/gcc/ppc64le-redhat-linux/13
Candidate multilib: .;@m64
Selected multilib: .;@m64
#
# pahole --version
v1.25
```

**Comment by isomorphik7** [comment]
log suggests that the JIT does not support calling a kernel function.
 
I disabled JIT, but that doesn't solve this problem. 

I don't have good grasp of bpf internals aside from the fact *.bpf.c is compiled with -target bpf and then loaded into kernel using bpftool, which I understand, is built through `Makefile` in `tools/sched_ext` along with libbpf binaries.

I don't understand which component is causing this load problem? is it the kernel version? is there something wrong with the libbpf version or the bpf program itself?

**Comment by htejun** [comment]
Alexei says that a number of BPF features are missing in ppc unfortunately - e.g. bpf trampoline (requirement for struct-ops) is only present on x86, s390, riscv, arm64.

**Comment by isomorphik7** [comment]
hmm..I got to know as well. I have switched to x86 based system now. And, I was able to build the custom kernel and the example scheduler following documentation : )

Thanks for the reply!
