### ISSUE TITLE
An error occurred while compiling atropos. 

### ISSUE THREAD

**Issue by Biyi-lab** [sched-ext/sched_ext#6]
The initial compilation and execution of the use case under tool/sched_ext went smoothly. However, after a while, an error occurred. I'm pretty sure I didn't change anything.  
```
scx_example_simple: scx_example_simple.c:86: main: Assertion `link' failed.
[1]    65346 IOT instruction (core dumped)  ./scx_example_simple
```

Another problem: An error occurred while compiling atropos. It seems like a problem with library version dependency, but I am not certain. As a potential solution, I attempt to modify the Makefile to exclude the compilation of atropos, and it works. However, this is not a satisfactory solution in the end.
```
error: failed to run custom build command for `libbpf-sys v1.1.1+v1.1.0`

Caused by:
  process didn't exit successfully: `/root/sched_ext/tools/sched_ext/atropos/target/release/build/libbpf-sys-e1ab36cde4ac9c05/build-script-build` (exit status: 101)
  --- stdout
  make[1]: Entering directory '/root/.cargo/registry/src/github.com-1ecc6299db9ec823/libbpf-sys-1.1.1+v1.1.0'
  make[1]: Leaving directory '/root/.cargo/registry/src/github.com-1ecc6299db9ec823/libbpf-sys-1.1.1+v1.1.0'

  --- stderr
  make[1]: *** No targets specified and no makefile found.  Stop.
  thread 'main' panicked at 'pkg-config is required to compile libbpf-sys using the vendored copy of libbpf', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/libbpf-sys-1.1.1+v1.1.0/build.rs:106:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `clang-sys v1.6.1`

Caused by:
  process didn't exit successfully: `/root/sched_ext/tools/sched_ext/atropos/target/release/build/clang-sys-4031e095defa8074/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'could not find any static libraries', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-1.6.1/build/static.rs:92:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
make: *** [Makefile:202: atropos] Error 101
```
Toolchain versions:
```
-> # clang --version
Ubuntu clang version 17.0.0 (++20230416052825+70b182e0d3f7-1~exp1~20230416172957.603)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

-> # llvm-config --version
17.0.0

-> # pahole --version
v1.24

-> # rustc --version
rustc 1.71.0-nightly (458d4dae8 2023-04-25)
```
Add: Rebooting can solve the first problem. `atropos` still compile errors.

**Comment by ByteLab-David** [comment]
Sorry for the delayed response, I was getting over COVID last week.

I'm not able to reproduce these build failures, even with the  same exact dependencies. Does doing a clean build help?

```
$ make LD=ld.lld LLVM=1 CC=clang clean
$ make LD=ld.lld LLVM=1 CC=clang -j
```

The error message makes it sound like you don't have `pkg-config` installed, but I'm not sure why that would have not triggered on the first compilation run.

Does `$ which pkg-config` show anything? If not, can you try installing `pkg-config` (https://www.freedesktop.org/wiki/Software/pkg-config/) and seeing if that helps?

**Comment by Biyi-lab** [comment]
Thanks for your reply.  Install `pkg-config` successfully resolves the `libbpf-sys v1.1.1+v1.1.0` error. However, the issue with `clang-sys v1.6.1` persists.
```
Compiling lazycell v1.3.0
   Compiling rustc-hash v1.1.0
error: failed to run custom build command for `clang-sys v1.6.1`

Caused by:
  process didn't exit successfully: `/root/sched_ext/tools/sched_ext/atropos/target/release/build/clang-sys-a8678a3995150b5d/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'could not find any static libraries', /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clang-sys-1.6.1/build/static.rs:92:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
make: *** [Makefile:201: atropos] Error 101
```

**Comment by ByteLab-David** [comment]
Hmm, so it looks like that's failing because the build system can't find a static clang library: ` libclang.a`. It looks like it checks for:

1. Inside of whatever directory is returned from `llvm-config --prefix`
2. Inside of `$LD_LIBRARY_PATH`
3. Inside of /usr/local, /usr/lib, etc

If there's no `libclang.a` anywhere in there, it'll fail.

I'm not sure how to get Ubuntu to install `libclang.a`. If there's a way then do that, otherwise you can build clang locally as follows:

```
$ git clone \
https://github.com/llvm/llvm-project.git llvm-project
$ mkdir -p llvm-project/build; cd llvm-project/build
$ mkdir -p ~/llvm-builds
$ cmake \
-G Ninja \
-DLLVM_TARGETS_TO_BUILD="BPF;X86" \
-DCMAKE_INSTALL_PREFIX="$HOME/llvm-builds/$(date +%Y%m%d)" \
-DBUILD_SHARED_LIBS=OFF \
-DLIBCLANG_BUILD_STATIC=ON \
-DCMAKE_BUILD_TYPE=Release \
-DLLVM_ENABLE_TERMINFO=OFF \
-DLLVM_ENABLE_PROJECTS="clang;lld" \
../llvm
$ ninja install -j$(nproc)
$ ln -s -f \
/$HOME/llvm-builds/$(date +%Y%m%d) \
/$HOME/llvm-builds/latest
```
and then add `$HOME/llvm-builds/latest/build/bin` to your $PATH

**Comment by ByteLab-David** [comment]
@htejun / @dschatzberg it's kind of unfortunate if folks _have_ to compile clang locally to get `libclang.a` just to build the example schedulers. I don't suppose this is something we could package for them and bundle with cargo or something?

**Comment by htejun** [comment]
Yeah, most distros don't ship .a and I see the same problem if I make libclang.a inaccessible. libbpf-sys by default links to .so but it looks like we're forcing it to link statically through:
```
bindgen = { version = "0.61.0", features = ["logging", "static"], default-features = false }
```
If I drop that "static"s from the Cargo file, I get:
```
error: failed to run custom build command for `scx_atropos v0.5.0 (/home/htejun/os/work1/tools/sched_ext/atropos)`

Caused by:
  process didn't exit successfully: `/home/htejun/os/work1/tools/sched_ext/atropos/target/debug/build/scx_atropos-9622dd393dc0119f/build-script-build` (exit status: 127)
  --- stderr
  /home/htejun/os/work1/tools/sched_ext/atropos/target/debug/build/scx_atropos-9622dd393dc0119f/build-script-build: error while loading shared libraries: libclang.so.17git: cannot open shared object file: No such file or directory
```
So, that doesn't work either unfortunately and I'm not sure dynamically linking libbpf is a good idea in the first place. I don't know the plumbing here that well but it *seems* like what we wanna do is linking libbpf statically which should be fine as we build that together but that ends up requiring libclang to be static too, which we don't necessarily want or need. I'm a bit out of my depth. Let's see if @dschatzberg hopefully has better ideas.

**Comment by Biyi-lab** [comment]
Thanks, compiling clang locally and obtaining libclang.a appeared to be a valid solution. 
Unfortunately, I encountered a new issue during the subsequent stages of compilation. 
```
cargo build --manifest-path=atropos/Cargo.toml --release
   Compiling libbpf-sys v1.1.1+v1.1.0
   Compiling cargo_metadata v0.14.2
   Compiling vsprintf v2.0.0
   Compiling fb_procfs v0.6.2 (https://github.com/facebookincubator/below.git?rev=f305730#f3057307)
   Compiling bitvec v1.0.1
error: empty search path given via `-L`

error: could not compile `libbpf-sys` (lib) due to previous error
warning: build failed, waiting for other jobs to finish...
make: *** [Makefile:201: atropos] Error 101
```
Despite my aspirations to conduct testing on the atropos scheduler, it appeared that the strict dependency of the library always posed some unexpected errors.

**Comment by violence-max** [comment]
I am so disappointed to hear that bad news. 
I was planning to use the sched-ext API to write several new scheduling classes to participate in the operating system's feature track. However, now we have less than a month left until the preliminary submission deadline, and our team hasn't even set up the environment. I'm extremely disappointed, and I hope the officials can provide some response.

**Comment by ByteLab-David** [comment]
We're looking at the Atropos build issue, but you don't need to build it if you want to build your own schedulers.

**Comment by htejun** [comment]
@PerryJS-sys, @violence-max, can you guys see whether the latest sched_ext branch fixes the build issue?

**Comment by ByteLab-David** [comment]
Based on https://github.com/sched-ext/sched_ext/issues/8 being opened, I think this is now fixed and can be closed.
