### ISSUE TITLE
Error in compiling scx_central

### ISSUE THREAD

**Issue by himadrics** [sched-ext/sched_ext#63]
Hello,

I am trying to compile scx_central from the current HEAD of sched_ext branch (52911e1040a0), and I am getting the following error:
```
scx_central.c: In function ‘main’:                                                                                                                                                            
scx_central.c:59:37: error: ‘struct scx_central__rodata’ has no member named ‘slice_ns’                                                                                                       
   59 |                         skel->rodata->slice_ns = strtoull(optarg, NULL, 0) * 1000;                                                                                                    
      |                                     ^~                                                                                                                                                
make: *** [Makefile:193: scx_central] Error 1
```
The same scheduler compiles fine on commit b41ddc324de6.

**Comment by ByteLab-David** [comment]
Hi @himadrics, I'm not able to reproduce this on my end. scx_central.bpf.c does have slice_ns in rodata: https://github.com/sched-ext/sched_ext/blob/sched_ext/tools/sched_ext/scx_central.bpf.c#L61, and I looked at the generated skeleton file in build/include/scx_central.skel.h to confirm.

Does doing a clean build perhaps fix the issue?

**Comment by himadrics** [comment]
Hi @Decave, I started over with a ```make distclean```. I then re-compile the kernel and manually removed the scx_central binary from tools/sched_ext/ (It was not removed by distclean). And then upon trying to recompile scx_central, I am still getting the same ```error: ‘struct scx_central__rodata’ has no member named ‘slice_ns’```.

**Comment by himadrics** [comment]
Hmm, I just noticed that the kernel version is also updated with the new set of changes that I am pulling. And there are changes in sched_ext build as well (e.g. binaries are now placed in build/bin). So just recompiling the new kernel was not enough, I also needed to install and run it before recompiling scx_central.
