### ISSUE TITLE
problem running scx_nest

### ISSUE THREAD

**Issue by JuliaLawall** [sched-ext/sched_ext#71]
In the nest_scheduler branch, I am able to run scx_central, but not scx_nest:

libbpf: prog 'nest_select_cpu': BPF program load failed: Permission denied
libbpf: prog 'nest_select_cpu': -- BEGIN PROG LOAD LOG --
reg type unsupported for arg#0 function nest_select_cpu#45
0: R1=ctx(off=0,imm=0) R10=fp0
; s32 BPF_STRUCT_OPS(nest_select_cpu, struct task_struct *p, s32 prev_cpu,
0: (79) r9 = *(u64 *)(r1 +8)          ; R1=ctx(off=0,imm=0) R9_w=scalar()
1: (79) r7 = *(u64 *)(r1 +0)
func 'select_cpu' arg0 has btf_id 199 type STRUCT 'task_struct'
2: R1=ctx(off=0,imm=0) R7_w=trusted_ptr_task_struct(off=0,imm=0)
; tctx = bpf_task_storage_get(&task_ctx_stor, p, 0, 0);
2: (18) r1 = 0xffff9612f9a01600       ; R1_w=map_ptr(off=0,ks=4,vs=16,imm=0)
4: (bf) r2 = r7                       ; R2_w=trusted_ptr_task_struct(off=0,imm=0) R7_w=trusted_ptr_task_struct(off=0,imm=0)
5: (b7) r3 = 0                        ; R3_w=0
6: (b7) r4 = 0                        ; R4_w=0
7: (85) call bpf_task_storage_get#156         ; R0_w=map_value_or_null(id=1,off=0,ks=4,vs=16,imm=0)
8: (b4) w8 = -2                       ; R8_w=4294967294
; if (!tctx)
9: (15) if r0 == 0x0 goto pc+175      ; R0_w=map_value(off=0,ks=4,vs=16,imm=0)
; p_mask = tctx->tmp_mask;
10: (79) r6 = *(u64 *)(r0 +0)         ; R0=map_value(off=0,ks=4,vs=16,imm=0) R6=scalar()
; if (!p_mask || !primary || !reserve)
11: (15) if r6 == 0x0 goto pc+173     ; R6=scalar()
; 
12: (18) r1 = 0xffff9612f9a01910      ; R1_w=map_value(off=0,ks=4,vs=16,imm=0)
14: (79) r1 = *(u64 *)(r1 +0)         ; R1_w=scalar()
15: (7b) *(u64 *)(r10 -24) = r1       ; R1_w=scalar() R10=fp0 fp-24_w=mmmmmmmm
; if (!p_mask || !primary || !reserve)
16: (15) if r1 == 0x0 goto pc+168     ; R1_w=scalar()
; 
17: (18) r1 = 0xffff9612f9a01918      ; R1_w=map_value(off=8,ks=4,vs=16,imm=0)
19: (79) r1 = *(u64 *)(r1 +0)         ; R1_w=scalar()
; if (!p_mask || !primary || !reserve)
20: (15) if r1 == 0x0 goto pc+164     ; R1_w=scalar()
21: (7b) *(u64 *)(r10 -48) = r1       ; R1_w=scalar() R10=fp0 fp-48_w=mmmmmmmm
22: (b4) w1 = 1                       ; R1_w=1
23: (7b) *(u64 *)(r10 -40) = r0       ; R0=map_value(off=0,ks=4,vs=16,imm=0) R10=fp0 fp-40_w=map_value
; tctx->force_local = true;
24: (73) *(u8 *)(r0 +12) = r1         ; R0=map_value(off=0,ks=4,vs=16,imm=0) R1_w=1
; idle_smtmask = scx_bpf_get_idle_smtmask();
25: (85) call scx_bpf_get_idle_smtmask#32415          ; R0=ptr_cpumask(ref_obj_id=2,off=0,imm=0) refs=2
26: (7b) *(u64 *)(r10 -32) = r9       ; R9=scalar() R10=fp0 fp-32_w=mmmmmmmm refs=2
27: (bf) r9 = r0                      ; R0=ptr_cpumask(ref_obj_id=2,off=0,imm=0) R9_w=ptr_cpumask(ref_obj_id=2,off=0,imm=0) refs=2
; prev_fully_idle = bpf_cpumask_test_cpu(prev_cpu, idle_smtmask);
28: (79) r1 = *(u64 *)(r10 -32)       ; R1_w=scalar() R10=fp0 fp-32_w=mmmmmmmm refs=2
29: (bf) r2 = r9                      ; R2_w=ptr_cpumask(ref_obj_id=2,off=0,imm=0) R9_w=ptr_cpumask(ref_obj_id=2,off=0,imm=0) refs=2
30: (85) call bpf_cpumask_test_cpu#81413      ; R0_w=scalar() refs=2
31: (bc) w8 = w0                      ; R0_w=scalar() R8_w=scalar(umax=4294967295,var_off=(0x0; 0xffffffff)) refs=2
; scx_bpf_put_idle_cpumask(idle_smtmask);
32: (bf) r1 = r9                      ; R1_w=ptr_cpumask(ref_obj_id=2,off=0,imm=0) R9_w=ptr_cpumask(ref_obj_id=2,off=0,imm=0) refs=2
33: (79) r9 = *(u64 *)(r10 -32)       ; R9_w=scalar() R10=fp0 fp-32_w=mmmmmmmm refs=2
34: (85) call scx_bpf_put_idle_cpumask#32422          ;
; bpf_cpumask_and(p_mask, p->cpus_ptr, cast_mask(primary));
35: (79) r2 = *(u64 *)(r7 +1176)      ; R2_w=rcu_ptr_cpumask(off=0,imm=0) R7=trusted_ptr_task_struct(off=0,imm=0)
; bpf_cpumask_and(p_mask, p->cpus_ptr, cast_mask(primary));
36: (bf) r1 = r6                      ; R1_w=scalar(id=3) R6=scalar(id=3)
37: (79) r3 = *(u64 *)(r10 -24)       ; R3_w=scalar() R10=fp0 fp-24=mmmmmmmm
38: (85) call bpf_cpumask_and#81381
R1 type=scalar expected=fp
processed 36 insns (limit 1000000) max_states_per_insn 0 total_states 3 peak_states 3 mark_read 3
-- END PROG LOAD LOG --
libbpf: prog 'nest_select_cpu': failed to load: -13
libbpf: failed to load object 'scx_nest'
libbpf: failed to load BPF skeleton 'scx_nest': -13
scx_nest.c:136 [scx panic]: Permission denied
Failed to load skel

**Comment by ByteLab-David** [comment]
I wasn't able to reproduce, but it's possibly because of compiler version differences?

>38: (85) call bpf_cpumask_and#81381
>R1 type=scalar expected=fp

For some reason, the verifier seems to think that the p_mask could be a scalar / `NULL`. Not sure why -- the BPF prog isn't sleepable so RCU protection should automatically apply. I manually specified RCU regions which should protect `p_mask` (as well as `primary` and `reserve`), and pushed it to the nest_scheduler branch. Could you please give it another try?

**Comment by ByteLab-David** [comment]
This was fixed by updating LLVM to >= 17
