### ISSUE TITLE
Compatibility with lockdown=confidentiality

### ISSUE THREAD

**Issue by extSunset** [sched-ext/sched_ext#72]
Not sure if this is the right place to address this question. Is there any chance that sched-ext will become compatible with `lockdown=confidentiality` in the future (it now works with `lockdown=integrity`)?

**Comment by htejun** [comment]
I'm not familiar with `lockdown=` but from the description the `confidentiality` setting seems clearly exclusive with BPF in general, so probably not.

**Comment by htejun** [comment]
Closing for now. Please feel free to reopen if you have further questions.
