### ISSUE TITLE
A question about how to print logs

### ISSUE THREAD

**Issue by ChenJY1221** [sched-ext/sched_ext#86]
Hi team,

This is an question, not an issue.

I use Buildroot to build my QEMU root file system ，and I run my compiled scheduler example on this system. Now I‘d like to know more details about how the scheduler examples work. So I wanna to print some logs while I run my scheduler examples like scx_central on the QEMU. Whether some good ways to help me add some functions in the scheduler examples and print the log I need?

**Comment by ByteLab-David** [comment]
Hi, the easiest thing to use is probably `bpf_printk()`. You can use it like a normal formatted print function, though beware that it does fail silently if the input is not correctly formatted.

To view the output, do:

```
# cat /sys/kernel/debug/tracing/trace_pipe
```

You're reading a ringbuffer, so note that it does have finite size. Here's an example:

```
void BPF_STRUCT_OPS(example_enable, struct task_struct *p,
		    struct scx_enable_args *args)
{
	bpf_printk("%s scheduled with sched_ext", p->comm);
}
```

Will print the name of every task as it's enabled to be scheduled with the currently running sched_ext scheduler.

**Comment by ChenJY1221** [comment]
@Decave  thx for you advice.
I've tried bpf_trace_printk() in my program.There were not errors occured.But I can't find my trace result file in the /sys/kernel/debug/tracing/trace_pipe because i can't my tracing folder under the path /sys/kernel/debug.Do you know what's the reason for this?

**Comment by ChenJY1221** [comment]
What's more,I'd like to know whether some efficient methods to debug my self-define scheduler under the bpf environment.

**Comment by htejun** [comment]
This most likely was a kernel config issue on tracing subsystem. Have you figured out? Now that we have pre-packaged kernels for arch and ubuntu, that probably is an easier way to try sched_ext. Please take a look at https://github.com/sched-ext/scx repo. Thanks.
